services:
  study-org-frontend:
    build: .
    environment:
      API_URL: ${API_URL:-/api}
      BACKEND_URL: ${BACKEND_URL:-http://95.111.238.203:3071}
      PORT: ${PORT:-3070}
    ports:
      - "${PORT:-3070}:3070"
    restart: unless-stopped
